name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: CI checks
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      # rust
      - name: install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      # cache cargo artifacts
      - name: cache cargo artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          # cache is invalidated on Cargo.lock changes
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          # if exact keys are not found, try with prefix
          restore-keys: |
            ${{ runner.os }}-cargo-

      # check licenses
      - name: check licenses
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check licenses

      # fmt
      - name: check formatting
        run: cargo fmt --all -- --check

      # clippy
      - name: check lints
        run: RUSTFLAGS="-D warnings" cargo clippy --all --all-targets --locked -- -D warnings

      # build
      - name: build with warnings as errors
        run: RUSTFLAGS="-D warnings" cargo build --all --verbose --locked

      # tests
      - name: run tests
        run: cargo test --all --locked --verbose
